In [ ]:
# X = WH

In [54]:
import numpy as np
X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])

In [55]:
from sklearn.decomposition import NMF
model = NMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_

In [56]:
model.reconstruction_err_

0.0011599349216012118

In [57]:
X

array([[ 1. ,  1. ],
       [ 2. ,  1. ],
       [ 3. ,  1.2],
       [ 4. ,  1. ],
       [ 5. ,  0.8],
       [ 6. ,  1. ]])

In [58]:
W

array([[ 0.        ,  0.46880684],
       [ 0.55699523,  0.3894146 ],
       [ 1.00331638,  0.41925352],
       [ 1.6733999 ,  0.22926926],
       [ 2.34349311,  0.03927954],
       [ 2.78981512,  0.06911798]])

In [59]:
H

array([[ 2.09783018,  0.30560234],
       [ 2.13443044,  2.13171694]])

In [69]:
X = 10*np.random.random((100,50))
model = NMF(n_components=5, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_

In [70]:
model.reconstruction_err_

180.34341934480062

In [71]:
X.shape

(100, 50)

In [72]:
W.shape

(100, 5)

In [73]:
H.shape

(5, 50)

In [74]:
X[:10,:5]

array([[ 1.66857765,  9.90401843,  7.54370794,  8.19881247,  1.15564786],
       [ 4.38172983,  5.95739145,  8.82768982,  0.2488335 ,  9.74659537],
       [ 1.98393563,  3.57768944,  7.29674314,  0.69756533,  5.70433258],
       [ 1.51157083,  6.80197521,  4.88405487,  0.80975147,  1.75795293],
       [ 7.28286642,  9.19456358,  8.13148749,  3.60142375,  9.83217243],
       [ 6.9359778 ,  0.06429647,  7.79061002,  6.07716244,  8.64538284],
       [ 0.30462464,  5.43864419,  6.48870468,  9.61092078,  1.18718029],
       [ 5.08397332,  6.40552092,  6.65329894,  6.8848461 ,  4.80268559],
       [ 6.20519838,  7.90109649,  0.57404398,  2.54485848,  7.79567164],
       [ 6.35020456,  2.57192165,  5.41833719,  2.08283996,  9.23846431]])

In [75]:
W[:10]

array([[ 2.30074991,  1.65360635,  1.04720426,  0.66066547,  0.93414528],
       [ 1.78391914,  0.        ,  0.17992193,  0.85733557,  2.15344987],
       [ 1.40020475,  1.28348194,  0.        ,  1.13718041,  1.4282305 ],
       [ 2.97448616,  0.02428993,  0.47062103,  0.79760467,  1.57683357],
       [ 0.        ,  0.35545189,  3.08990579,  0.90949686,  0.9197206 ],
       [ 1.52626619,  1.13291925,  0.26280162,  0.76267819,  1.59134575],
       [ 1.2707438 ,  2.65967888,  1.10725502,  0.87219556,  0.04407863],
       [ 0.        ,  2.00989062,  0.79204881,  0.16783671,  1.99140098],
       [ 1.67470255,  1.80358398,  2.01493592,  0.11448384,  0.74301156],
       [ 2.3013708 ,  0.        ,  1.22973711,  1.00151584,  1.29758224]])