In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target


In [ ]:
from sklearn.preprocessing import LabelBinarizer
df = df[df.species.isin([0,1])]

In [3]:
df.shape

(100, 5)

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.preprocessing import OneHotEncoder

df = df[df.species.isin([0,1])]
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [6]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train,y_train)
y_pred_proba = clf.predict_proba(X_test)

In [10]:
y_pred_proba[:5]

array([[ 0.95129549,  0.04870451],
       [ 0.01483491,  0.98516509],
       [ 0.96776508,  0.03223492],
       [ 0.01227605,  0.98772395],
       [ 0.02534699,  0.97465301]])

In [13]:
from sklearn.metrics import accuracy_score, roc_auc_score

print(accuracy_score(y_test, clf.predict(X_test)))
print(roc_auc_score(y_test, y_pred_proba[:,1]))

1.0
1.0


In [22]:
from sklearn.metrics import roc_curve, auc

fpr, tpr, thres = roc_curve(y_test, y_pred_proba[:,1])
roc_auc = auc(fpr, tpr)

In [23]:
thres

array([ 0.99059657,  0.92746678,  0.00802467])

In [24]:
fpr

array([ 0.,  0.,  1.])

In [2]:

plt.plot(fpr, tpr,
         label='Area = %.2f)' %roc_auc)

plt.plot(fpr, tpr, 'rx')

plt.plot([0, 1], [0, 1], 'k--')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend(loc="lower right")
plt.show()

NameError: name 'plt' is not defined