In [1]:
import numpy as np

## array

In [2]:
print np.array([1,2,3,4])
print np.array([[1,2],[3,4]])
print np.ones(3)
print np.zeros(3)
print np.arange(0, 10, 2)
print np.arange(1, 7, 1).reshape(2,3)

[1 2 3 4]
[[1 2]
 [3 4]]
[ 1.  1.  1.]
[ 0.  0.  0.]
[0 2 4 6 8]
[[1 2 3]
 [4 5 6]]


## indexing

In [3]:
v = np.array([1,2,3,4])
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print v[0]
print v[0:2]

print A[0,1]  # cell
print A[0]  # row
print A[:, 1]  # col
print A[0:2, 1]

1
[1 2]
2
[1 2 3]
[2 5 8]
[2 5]


## array operation

In [4]:
# list concat
arr_py = [1,2,3,4]
print arr_py + arr_py

# vector operation
arr_n
p = np.array([1,2,3,4])
print arr_np + arr_np  

# numpy array concat
print np.concatenate((arr_np, arr_np), axis=0)  

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
[1 2 3 4 1 2 3 4]


## join array

In [5]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print np.concatenate([A,B], axis=0)  # join row
print np.concatenate([A,B], axis=1)  # join col

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## matrix operation

In [6]:
A = np.array([[1,1],[0,1]])
B = np.array([[1,2],[3,4]])

print A+A
print A*B  # elementwise multiplication
print A*5
print B**2
print A.dot(A)  # matrix multiplication
print B.transpose()

[[2 2]
 [0 2]]
[[1 2]
 [0 4]]
[[5 5]
 [0 5]]
[[ 1  4]
 [ 9 16]]
[[1 2]
 [0 1]]
[[1 3]
 [2 4]]


## api

In [7]:
arr = np.array([1,2,3,4])

print arr.mean()
print arr.std()
print arr.min()
print arr.max()
print arr.sum()

2.5
1.11803398875
1
4
10


## random

In [8]:
print np.random.random(5)
print np.random.normal(100, 1, 5)
print np.random.randint(0,10, 5)

[ 0.04948112  0.04019462  0.43890594  0.04277935  0.46102606]
[  98.80819595  100.03581375  100.55202471  100.52000708   99.44744483]
[0 0 1 8 9]


## read

In [11]:
data = np.genfromtxt('house.csv', delimiter=',')
print data[0:10,:]

[[  6.1101  17.592 ]
 [  5.5277   9.1302]
 [  8.5186  13.662 ]
 [  7.0032  11.854 ]
 [  5.8598   6.8233]
 [  8.3829  11.886 ]
 [  7.4764   4.3483]
 [  8.5781  12.    ]
 [  6.4862   6.5987]
 [  5.0546   3.8166]]
